### ISSUE TITLE
Default SSLSessionCache path not changeable

### ISSUE THREAD

**Issue by kusw3** [AtlasIT-AM/eyp-apache#96]
At least, seen in Centos7. Default path for ssl session cache is hardcoded in ssl.erb. While that path is valid for some mod_ssl installation as a default it seems to have been changed in Centos7 at least.

[root@apacheserver1 ~]# rpm -ql mod_ssl.x86_64
/etc/httpd/conf.d/ssl.conf
/etc/httpd/conf.modules.d/00-ssl.conf
/usr/lib64/httpd/modules/mod_ssl.so
/usr/libexec/httpd-ssl-pass-dialog
**/var/cache/httpd/ssl**

**Comment by jordiprats** [comment]
Fixed in PR97
